name: 'Sous Builder'
description: 'A builder recipe for Sous drupal project.'
type: 'Site'

install:
  - field
  - file
  - image
  - link
  - media
  - media_library
  - metatag
  - node
  - paragraphs
  - path
  - taxonomy
  - text
  - views
  - views_ui
config:
  import:
    field: '*'
    file: '*'
    image: '*'
    link: '*'
    media: '*'
    media_library: '*'
    metatag: '*'
    node: '*'
    paragraphs: '*'
    path: '*'
    taxonomy: '*'
    text: '*'
